source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'modeling_kgroup' do
    pod 'SnapKit', '~> 4.0.0'
		pod 'Material', '~> 2.0'
		pod 'Then'
		pod "AMXFontAutoScale"
		pod 'Graph', '~> 2.0'
end

